#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# API Routes
api_routes:
    resource:
        path: '../src/Controller/Api'
        namespace: App\Controller\Api
    type: attribute
    prefix: /api

# Frontend routes (legacy)
app:
    resource:
        path: '../pages'
    type: glob
    path: /{file}.html
    controller: App\Controller\Frontend\PageController::serve
    requirements:
        file: '.+'
