# This file is the entry point to configure your own services
# Place the following lines at the top of the file to learn about service discovery and auto wiring
# Learn more about service discovery and auto-wiring in Symfony docs
# https://symfony.com/doc/current/service_container.html#services-load-classes-namespace-as-service

parameters:
    env(DATABASE_URL): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
